// apps/react/src/Fetch.tsx
import React from "react";

export const Fetch = (props: { url: string }) => {
  const [greeting, setGreeting] = React.useState("");
  const [error, setError] = React.useState("");

  async function loadGreeting() {
    try {
      const response = await fetch(new URL(props.url, location.href));
      const data = await response.json();
      setGreeting(data.greeting);
    } catch (error) {
      setError("Oops, failed to fetch!");
    }
  }

  return (
    <div>
      <button disabled={!!greeting} onClick={loadGreeting}>
        Load Greeting
      </button>
      {greeting ? <h1>{greeting}</h1> : null}
      {error ? <h1 role="alert">{error}</h1> : null}
    </div>
  );
};

// apps/vue/src/Fetch.vue
<script setup lang="ts">
import { ref } from "vue";

const greeting = ref("");
const error = ref("");

const props = defineProps({
  url: {
    type: String,
    required: true,
  },
});

const loadGreeting = async () => {
  try {
    const response = await fetch(new URL(props.url, location.href));
    const data = await response.json();
    greeting.value = data.greeting;
  } catch (_) {
    error.value = "Oops, failed to fetch!";
  }
};
</script>

<template>
  <div>
    <button :disabled="!!greeting" @click="loadGreeting">Load Greeting</button>
    <h1 v-if="!!greeting">{{ greeting }}</h1>
    <h1 v-if="!!error" role="alert">{{ error }}</h1>
  </div>
</template>
